# Generated by Django 3.0.3 on 2020-03-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dororo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pertenencia',
            new_name='bolsa',
        ),
    ]
