# Generated by Django 3.0.3 on 2020-03-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dororo', '0002_auto_20200310_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bolsa',
            new_name='objeto',
        ),
    ]
